/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvenance = "synthetic" | "production";
export type DataThroughDate = string;
export type DataThroughWeek = string;
export type Dayparts = Daypart[] | null;
export type FromHour = number;
export type Id = string;
export type Label = string;
export type ToHour = number;
export type AsOf = string;
export type Bachelor = number;
export type Master = number;
export type Source = string;
export type FirstWeek = string;
export type Text = string;
export type GeneratedAt = string;
export type PipelineVersion = string;
export type PrivacyFloorN = number;
export type SchemaVersion = string;
export type ByStatus = {
  [k: string]: LanguageTotals;
} | null;
export type De = OkCell | SuppressedCell;
export type Status = "ok";
export type Value = number;
export type Status1 = "suppressed";
export type En = OkCell | SuppressedCell;
export type Other = OkCell | SuppressedCell;
export type Undetermined = OkCell | SuppressedCell;
export type FootnoteIds = string[] | null;
export type Cell = OkCell | SuppressedCell;
export type Week = string;
export type Series = WeeklyEntry[];
export type FootnoteIds1 = string[] | null;
export type WeeklyByStatus = {
  [k: string]: LanguageWeekly;
} | null;
export type ByStatus1 = {
  [k: string]: PerStudentByStatus;
} | null;
export type Cell1 = OkCell | SuppressedCell;
export type Hi = number | null;
export type Lo = number;
export type Bins = HistogramBin[];
export type FootnoteIds2 = string[] | null;
export type NTotal = OkCell | SuppressedCell;
export type Summary = (OkSummaryStats | SuppressedSummaryStats) | null;
export type Mean = number | null;
export type Median = number;
export type NStudents = number;
export type P25 = number;
export type P75 = number;
export type Sd = number | null;
export type Status2 = "ok";
export type Status3 = "suppressed";
export type Unit = string;
export type ByStatus2 = {
  [k: string]: SessionsByStatus;
} | null;
export type Cell2 = OkCell | SuppressedCell;
export type Dow = number;
export type Hour = number;
export type Cells = HeatmapCell[];
export type FootnoteIds3 = string[] | null;
export type ByStatus3 = {
  [k: string]: TemporalUsageByStatus;
} | null;
export type Cell3 = OkCell | SuppressedCell;
export type Daypart1 = string;
export type Dow1 = number;
export type Cells1 = DaypartCell[];
export type FootnoteIds4 = string[] | null;
export type FootnoteIds5 = string[] | null;
export type Weekday = OkCell | SuppressedCell;
export type Weekend = OkCell | SuppressedCell;
export type SemesterProfiles = SemesterProfile[] | null;
export type FootnoteIds6 = string[] | null;
export type Kind = "summer" | "winter";
export type Label1 = string;
export type ActiveStudents = OkCell | SuppressedCell;
export type Messages = OkCell | SuppressedCell;
export type SemesterWeek = number;
export type Week1 = string;
export type Points = SemesterProfilePoint[];
export type WindowId = string;
export type WeeklyByStatus1 = {
  [k: string]: TemporalUsageWeekly;
} | null;
export type ByStatus4 = {
  [k: string]: TopicGroup;
} | null;
export type FootnoteIds7 = string[] | null;
export type Cell4 = OkCell | SuppressedCell;
export type Description = string | null;
export type Label2 = string;
export type Items = TopicItem[];
export type NTotal1 = OkCell | SuppressedCell;
export type ThemeSetVersion = string | null;
export type Baseline = (WindowBaseline | WeeksBaseline | TrajectoryBaseline) | null;
export type Kind1 = "window";
export type WindowId1 = string;
export type From = string;
export type Kind2 = "weeks";
export type Through = string;
export type Kind3 = "trajectory";
/**
 * @maxItems 5
 */
export type Findings =
  | []
  | [Finding]
  | [Finding, Finding]
  | [Finding, Finding, Finding]
  | [Finding, Finding, Finding, Finding]
  | [Finding, Finding, Finding, Finding, Finding];
export type NStudents1 = number;
export type Value1 = number;
export type Delta = number;
export type Evidence = "robust" | "indicative";
export type FootnoteIds8 = string[] | null;
export type Id1 = string;
export type Kind4 = "rate" | "share" | "median";
export type Measure = string;
export type Method = string;
export type Tab = "topics" | "adoption" | "engagement" | "timing" | "language";
export type Title = string;
export type Trajectory = TrajectoryPoint[] | null;
export type NStudents2 = number;
export type Value2 = number;
export type WindowId2 = string;
export type Unit1 = string;
export type InsufficientData = boolean;
export type ByStatus5 = {
  [k: string]: UsageContextByStatus;
} | null;
export type ActiveStudents1 = OkCell | SuppressedCell;
export type FootnoteIds9 = string[] | null;
export type Messages1 = OkCell | SuppressedCell;
export type NewRegistrations = (OkCell | SuppressedCell) | null;
export type NewRegistrationsActive = (OkCell | SuppressedCell) | null;
export type NewUsers = (OkCell | SuppressedCell) | null;
export type ReturningUsers = (OkCell | SuppressedCell) | null;
export type Sessions = (OkCell | SuppressedCell) | null;
export type FootnoteIds10 = string[] | null;
export type Frequent = (OkCell | SuppressedCell) | null;
export type Monthly = OkCell | SuppressedCell;
export type OneTime = OkCell | SuppressedCell;
export type Sporadic = OkCell | SuppressedCell;
export type ActiveStudents2 = OkCell | SuppressedCell;
export type FootnoteIds11 = string[] | null;
export type Messages2 = OkCell | SuppressedCell;
export type NewRegistrations1 = OkCell | SuppressedCell;
export type NewRegistrationsActive1 = (OkCell | SuppressedCell) | null;
export type NewUsers1 = (OkCell | SuppressedCell) | null;
export type ReturningUsers1 = (OkCell | SuppressedCell) | null;
export type Sessions1 = OkCell | SuppressedCell;
export type Timezone = string;
export type From1 = string;
export type Through1 = string;
export type Id2 = string;
export type Kind5 = "all_time";
export type Label3 = string;
export type ShortLabel = string | null;
export type EndDate = string;
export type Id3 = string;
export type Kind6 = "semester";
export type Label4 = string;
export type ShortLabel1 = string | null;
export type StartDate = string;
export type Weeks = string[];
export type Id4 = string;
export type Kind7 = "semester_slice";
export type Label5 = string;
export type ParentWindowId = string;
/**
 * @minItems 2
 * @maxItems 2
 */
export type SemesterWeeks = [number, number];
export type ShortLabel2 = string;
export type Weeks1 = string[];
export type Id5 = string;
export type Kind8 = "trailing";
export type Label6 = string;
export type Weeks2 = string[];
export type Windows = (AllTimeWindow | SemesterWindow | SemesterSliceWindow | TrailingWindow)[];

/**
 * Root of the aggregates file. Shape law lives here; semantics in docs/aggregates-contract.md.
 */
export interface Aggregates {
  data_provenance: DataProvenance;
  data_through_date: DataThroughDate;
  data_through_week: DataThroughWeek;
  dayparts?: Dayparts;
  enrollment?: Enrollment | null;
  first_week: FirstWeek;
  footnotes: Footnotes;
  generated_at: GeneratedAt;
  label_versions: LabelVersions;
  pipeline_version: PipelineVersion;
  privacy_floor_n: PrivacyFloorN;
  schema_version: SchemaVersion;
  sections: Sections;
  timezone: Timezone;
  windows: Windows;
  [k: string]: unknown;
}
/**
 * One block of the day, in the registry at document root (1.6.0, D-54).
 *
 * Boundaries live in the document rather than in dashboard code for the same reason
 * footnote texts do: a definition is versioned with the numbers it governs, and an
 * archived blob must still say what its own cells meant. `from_hour` is inclusive,
 * `to_hour` exclusive; the registry partitions 0..24 contiguously, so no block wraps
 * midnight and `hour // width` is a valid lookup.
 */
export interface Daypart {
  from_hour: FromHour;
  id: Id;
  label: Label;
  to_hour: ToHour;
  [k: string]: unknown;
}
export interface Enrollment {
  per_window: PerWindow;
  [k: string]: unknown;
}
export interface PerWindow {
  [k: string]: EnrollmentEntry;
}
/**
 * How many students were enrolled in a program level during one window (1.7.0, D-55).
 *
 * Not a measurement, which is why this lives outside `sections` and carries plain ints
 * rather than CountCells. Nothing here passes floored_count because there is nothing to
 * floor: an institutional headcount is not a count over students who wrote messages, and
 * dressing it as a cell would invite exactly that misreading.
 */
export interface EnrollmentEntry {
  as_of: AsOf;
  bachelor: Bachelor;
  master: Master;
  source: Source;
  [k: string]: unknown;
}
export interface Footnotes {
  [k: string]: Footnote;
}
export interface Footnote {
  text: Text;
  [k: string]: unknown;
}
export interface LabelVersions {
  [k: string]: string;
}
export interface Sections {
  language?: LanguageSection | null;
  per_student?: PerStudentSection | null;
  sessions?: SessionsSection | null;
  temporal_usage?: TemporalUsage | null;
  topics?: TopicsSection | null;
  trends?: TrendsSection | null;
  usage_context?: UsageContext | null;
  [k: string]: unknown;
}
export interface LanguageSection {
  per_window: PerWindow1;
  weekly: LanguageWeekly;
  weekly_by_status?: WeeklyByStatus;
  [k: string]: unknown;
}
export interface PerWindow1 {
  [k: string]: LanguageWindow;
}
export interface LanguageWindow {
  by_status?: ByStatus;
  totals: LanguageTotals;
  [k: string]: unknown;
}
export interface LanguageTotals {
  de: De;
  en: En;
  other: Other;
  undetermined: Undetermined;
  [k: string]: unknown;
}
export interface OkCell {
  status: Status;
  value: Value;
  [k: string]: unknown;
}
export interface SuppressedCell {
  status: Status1;
  [k: string]: unknown;
}
export interface LanguageWeekly {
  messages_by_language: MessagesByLanguage;
  [k: string]: unknown;
}
export interface MessagesByLanguage {
  de: WeeklySeries;
  en: WeeklySeries;
  footnote_ids?: FootnoteIds1;
  other: WeeklySeries;
  undetermined: WeeklySeries;
  [k: string]: unknown;
}
export interface WeeklySeries {
  footnote_ids?: FootnoteIds;
  series: Series;
  [k: string]: unknown;
}
export interface WeeklyEntry {
  cell: Cell;
  week: Week;
  [k: string]: unknown;
}
export interface PerStudentSection {
  per_window: PerWindow2;
  [k: string]: unknown;
}
export interface PerWindow2 {
  [k: string]: PerStudentWindow;
}
/**
 * Engagement breadth: one observation per student, not per session (1.5.0, D-53).
 *
 * The `sessions` section above bins sessions; these bin the students behind them.
 * Nothing here is derivable from that section or from `usage_context.totals`:
 * dividing two floored totals yields a mean and says nothing about the spread,
 * which for every one of these three is where the finding lives (invariant 4).
 */
export interface PerStudentWindow {
  by_status?: ByStatus1;
  messages_per_student: Histogram;
  sessions_per_student: Histogram;
  weeks_active_per_student: Histogram;
  [k: string]: unknown;
}
/**
 * Engagement breadth for one program level (1.7.0, D-55).
 */
export interface PerStudentByStatus {
  messages_per_student: Histogram;
  sessions_per_student: Histogram;
  weeks_active_per_student: Histogram;
  [k: string]: unknown;
}
export interface Histogram {
  bins: Bins;
  footnote_ids?: FootnoteIds2;
  n_total: NTotal;
  summary?: Summary;
  unit: Unit;
  [k: string]: unknown;
}
export interface HistogramBin {
  cell: Cell1;
  hi: Hi;
  lo: Lo;
  [k: string]: unknown;
}
export interface OkSummaryStats {
  mean?: Mean;
  median: Median;
  n_students: NStudents;
  p25: P25;
  p75: P75;
  sd?: Sd;
  status: Status2;
  [k: string]: unknown;
}
export interface SuppressedSummaryStats {
  status: Status3;
  [k: string]: unknown;
}
export interface SessionsSection {
  per_window: PerWindow3;
  [k: string]: unknown;
}
export interface PerWindow3 {
  [k: string]: SessionsWindow;
}
export interface SessionsWindow {
  by_status?: ByStatus2;
  messages_per_session: Histogram;
  session_duration_minutes: Histogram;
  [k: string]: unknown;
}
/**
 * Conversation depth for one program level (1.7.0, D-55).
 */
export interface SessionsByStatus {
  messages_per_session: Histogram;
  session_duration_minutes: Histogram;
  [k: string]: unknown;
}
export interface TemporalUsage {
  per_window: PerWindow4;
  semester_profiles?: SemesterProfiles;
  weekly: TemporalUsageWeekly;
  weekly_by_status?: WeeklyByStatus1;
  [k: string]: unknown;
}
export interface PerWindow4 {
  [k: string]: TemporalUsageWindow;
}
export interface TemporalUsageWindow {
  activity_heatmap: HeatmapGrid;
  by_status?: ByStatus3;
  daypart_heatmap?: DaypartGrid | null;
  daypart_totals?: DaypartTotals | null;
  [k: string]: unknown;
}
export interface HeatmapGrid {
  cells: Cells;
  footnote_ids?: FootnoteIds3;
  [k: string]: unknown;
}
export interface HeatmapCell {
  cell: Cell2;
  dow: Dow;
  hour: Hour;
  [k: string]: unknown;
}
/**
 * Timing for one program level (1.7.0, D-55).
 *
 * `activity_heatmap` is deliberately absent: the 7x24 grid has been unrendered since
 * D-54 and is 44 KB of the document on its own, so three more copies would buy nothing.
 * A split that leaves it out is not a smaller version of the cohort-wide window — it is
 * the part the dashboard actually draws.
 */
export interface TemporalUsageByStatus {
  daypart_heatmap: DaypartGrid;
  daypart_totals: DaypartTotals;
  [k: string]: unknown;
}
/**
 * Weekday x daypart activity (1.6.0, D-54) — the coarse twin of HeatmapGrid.
 *
 * Density is checked at document root, not here: it is 7 x len(dayparts) and only the
 * root knows the registry. HeatmapGrid can self-check because 24 is a constant.
 */
export interface DaypartGrid {
  cells: Cells1;
  footnote_ids?: FootnoteIds4;
  [k: string]: unknown;
}
export interface DaypartCell {
  cell: Cell3;
  daypart: Daypart1;
  dow: Dow1;
  [k: string]: unknown;
}
export interface DaypartTotals {
  by_daypart: ByDaypart;
  footnote_ids?: FootnoteIds5;
  weekday: Weekday;
  weekend: Weekend;
  [k: string]: unknown;
}
export interface ByDaypart {
  [k: string]: OkCell | SuppressedCell;
}
/**
 * One semester re-indexed to teaching week, for the cross-semester overlay (1.6.0).
 *
 * `messages` is what the dashboard plots; `active_students` rides along because cohorts
 * differ in size (2025S 165 vs 2026S 117) and it is the size-robust read — publishing
 * both means a later toggle is a dashboard change, not another schema bump.
 */
export interface SemesterProfile {
  footnote_ids?: FootnoteIds6;
  kind: Kind;
  label: Label1;
  points: Points;
  window_id: WindowId;
  [k: string]: unknown;
}
export interface SemesterProfilePoint {
  active_students: ActiveStudents;
  messages: Messages;
  semester_week: SemesterWeek;
  week: Week1;
  [k: string]: unknown;
}
export interface TemporalUsageWeekly {
  active_students: WeeklySeries;
  messages: WeeklySeries;
  sessions: WeeklySeries;
  [k: string]: unknown;
}
export interface TopicsSection {
  per_window: PerWindow5;
  theme_set_version?: ThemeSetVersion;
  [k: string]: unknown;
}
export interface PerWindow5 {
  [k: string]: TopicsWindowEntry;
}
export interface TopicsWindowEntry {
  by_status?: ByStatus4;
  deductive: TopicDistribution;
  emergent_themes?: TopicDistribution | null;
  method_themes: TopicDistribution;
  software_themes: TopicDistribution;
  [k: string]: unknown;
}
export interface TopicGroup {
  deductive: TopicDistribution;
  emergent_themes?: TopicDistribution | null;
  method_themes: TopicDistribution;
  software_themes: TopicDistribution;
  [k: string]: unknown;
}
export interface TopicDistribution {
  footnote_ids?: FootnoteIds7;
  items: Items;
  n_total: NTotal1;
  [k: string]: unknown;
}
export interface TopicItem {
  cell: Cell4;
  description?: Description;
  label: Label2;
  [k: string]: unknown;
}
export interface TrendsSection {
  per_window: PerWindow6;
  [k: string]: unknown;
}
export interface PerWindow6 {
  [k: string]: TrendsWindow;
}
export interface TrendsWindow {
  baseline?: Baseline;
  findings?: Findings;
  insufficient_data?: InsufficientData;
  [k: string]: unknown;
}
export interface WindowBaseline {
  kind: Kind1;
  window_id: WindowId1;
  [k: string]: unknown;
}
export interface WeeksBaseline {
  from: From;
  kind: Kind2;
  through: Through;
  [k: string]: unknown;
}
export interface TrajectoryBaseline {
  kind: Kind3;
  [k: string]: unknown;
}
export interface Finding {
  baseline: MeasureValue;
  current: MeasureValue;
  delta: Delta;
  evidence: Evidence;
  footnote_ids?: FootnoteIds8;
  id: Id1;
  kind: Kind4;
  measure: Measure;
  method: Method;
  tab: Tab;
  title: Title;
  trajectory?: Trajectory;
  unit: Unit1;
  [k: string]: unknown;
}
export interface MeasureValue {
  n_students: NStudents1;
  value: Value1;
  [k: string]: unknown;
}
export interface TrajectoryPoint {
  n_students: NStudents2;
  value: Value2;
  window_id: WindowId2;
  [k: string]: unknown;
}
export interface UsageContext {
  per_window: PerWindow7;
  weekly: UsageContextWeekly;
  [k: string]: unknown;
}
export interface PerWindow7 {
  [k: string]: UsageContextWindow;
}
export interface UsageContextWindow {
  by_status?: ByStatus5;
  totals: UsageContextTotals;
  user_classes: UserClasses;
  [k: string]: unknown;
}
/**
 * Adoption by program level (1.4.0, D-50; the D-39 usage-time rule).
 *
 * 1.7.0 (D-55) widens this from the two measures the by-level card needed to what the
 * KPI tiles need, because the level filter now scopes the whole tab.
 *
 * 1.9.0 (D-59) adds the signup pair, reversing D-55's "and will not be". The old
 * reasoning — a registration has no session, so the usage-time rule does not reach it —
 * described the *implementation* (levels were resolved from a session's start) rather
 * than the data: the roster row carries the transition semester, and a registration
 * carries a date, which is all `status.status_at` needs. A 2026-08-01 probe found all
 * 550 registrants covered by the roster, 131 of whom never wrote a message — the
 * population the usage-time rule structurally cannot see. Both halves are split
 * together; splitting only the `_active` half would still be worse than not splitting.
 */
export interface UsageContextByStatus {
  active_students: ActiveStudents1;
  footnote_ids?: FootnoteIds9;
  messages: Messages1;
  new_registrations?: NewRegistrations;
  new_registrations_active?: NewRegistrationsActive;
  new_users?: NewUsers;
  returning_users?: ReturningUsers;
  sessions?: Sessions;
  user_classes?: UserClasses | null;
  [k: string]: unknown;
}
export interface UserClasses {
  footnote_ids?: FootnoteIds10;
  frequent?: Frequent;
  monthly: Monthly;
  one_time: OneTime;
  sporadic: Sporadic;
  [k: string]: unknown;
}
export interface UsageContextTotals {
  active_students: ActiveStudents2;
  footnote_ids?: FootnoteIds11;
  messages: Messages2;
  new_registrations: NewRegistrations1;
  new_registrations_active?: NewRegistrationsActive1;
  new_users?: NewUsers1;
  returning_users?: ReturningUsers1;
  sessions: Sessions1;
  [k: string]: unknown;
}
export interface UsageContextWeekly {
  registrations: WeeklySeries;
  [k: string]: unknown;
}
export interface AllTimeWindow {
  coverage: Coverage;
  id: Id2;
  kind: Kind5;
  label: Label3;
  short_label?: ShortLabel;
  [k: string]: unknown;
}
export interface Coverage {
  from: From1;
  through: Through1;
  [k: string]: unknown;
}
export interface SemesterWindow {
  coverage: Coverage;
  end_date: EndDate;
  id: Id3;
  kind: Kind6;
  label: Label4;
  short_label?: ShortLabel1;
  start_date: StartDate;
  weeks: Weeks;
  [k: string]: unknown;
}
/**
 * The closing stretch of one semester (1.8.0, D-56).
 *
 * Replaces `TrailingWindow`, which was anchored on the axis and therefore advanced with
 * extraction whether or not anyone was in class — across a break it drifted into weeks
 * holding almost nothing, which is where "recent" was least useful and most looked at.
 * A slice is anchored inside its semester instead, so during teaching weeks it is exactly
 * what the trailing window showed and across breaks it keeps pointing at the last weeks
 * that meant something.
 *
 * `weeks` is always a contiguous tail of the parent's *covered* weeks, so an id is stable
 * in MEANING — `2026S.last1` names the same span in every publish that contains it, which
 * `trailing_4` never did — but not in PRESENCE: only the anchor semester is sliced (D-57),
 * so `2026S.last1` leaves the registry once WS 2026 opens.
 */
export interface SemesterSliceWindow {
  coverage: Coverage;
  id: Id4;
  kind: Kind7;
  label: Label5;
  parent_window_id: ParentWindowId;
  semester_weeks: SemesterWeeks;
  short_label: ShortLabel2;
  weeks: Weeks1;
  [k: string]: unknown;
}
/**
 * DEPRECATED, unemitted since 1.8.0 (D-56) — kept so the *previous* publish still parses.
 *
 * Semester slices replaced this window, and deleting the member outright looked free
 * because nothing produces one. It is not: the API validates every blob it fetches
 * against the schema it ships with (contract §11), so the moment a 1.8.0 API met the
 * 1.7.0 document already sitting in the blob, `kind: "trailing"` would match no member of
 * the union and the dashboard would go down with a 500 — until the new blob was uploaded,
 * with no safe order to do the two halves in.
 *
 * So it stays for one release. Remove it once no reachable blob contains one, which
 * includes the rollback target.
 *
 * What this does and does not buy, stated exactly, because the difference matters when
 * someone is reading it under pressure: it makes the *deploy* safe in one direction —
 * ship the bundle and API first, and the 1.7.0 document already in the blob keeps
 * parsing, so there is no window where the site is down waiting for the upload. It does
 * NOT make a rollback free once the 1.8.0 blob has been uploaded: a rolled-back 1.7.0 API
 * cannot parse `semester_slice`, so after publishing, reverting the code means restoring
 * the previous blob in the same move. Blobs are immutable and versioned, so that is
 * available — it is a step to remember, not a trap.
 */
export interface TrailingWindow {
  coverage: Coverage;
  id: Id5;
  kind: Kind8;
  label: Label6;
  weeks: Weeks2;
  [k: string]: unknown;
}
