/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvenance = "synthetic" | "production";
export type DataThroughDate = string;
export type DataThroughWeek = string;
export type FirstWeek = string;
export type Text = string;
export type GeneratedAt = string;
export type PipelineVersion = string;
export type PrivacyFloorN = number;
export type SchemaVersion = string;
export type De = OkCell | SuppressedCell;
export type Status = "ok";
export type Value = number;
export type Status1 = "suppressed";
export type En = OkCell | SuppressedCell;
export type Other = OkCell | SuppressedCell;
export type Undetermined = OkCell | SuppressedCell;
export type FootnoteIds = string[] | null;
export type Cell = OkCell | SuppressedCell;
export type Week = string;
export type Series = WeeklyEntry[];
export type FootnoteIds1 = string[] | null;
export type Cell1 = OkCell | SuppressedCell;
export type Hi = number | null;
export type Lo = number;
export type Bins = HistogramBin[];
export type FootnoteIds2 = string[] | null;
export type NTotal = OkCell | SuppressedCell;
export type Summary = (OkSummaryStats | SuppressedSummaryStats) | null;
export type Mean = number | null;
export type Median = number;
export type NStudents = number;
export type P25 = number;
export type P75 = number;
export type Sd = number | null;
export type Status2 = "ok";
export type Status3 = "suppressed";
export type Unit = string;
export type Cell2 = OkCell | SuppressedCell;
export type Dow = number;
export type Hour = number;
export type Cells = HeatmapCell[];
export type FootnoteIds3 = string[] | null;
export type ActiveStudents = OkCell | SuppressedCell;
export type Messages = OkCell | SuppressedCell;
export type NewRegistrations = OkCell | SuppressedCell;
export type Sessions = OkCell | SuppressedCell;
export type FootnoteIds4 = string[] | null;
export type Monthly = OkCell | SuppressedCell;
export type OneTime = OkCell | SuppressedCell;
export type Sporadic = OkCell | SuppressedCell;
export type Timezone = string;
export type From = string;
export type Through = string;
export type Id = string;
export type Kind = "all_time";
export type Label = string;
export type EndDate = string;
export type Id1 = string;
export type Kind1 = "semester";
export type Label1 = string;
export type StartDate = string;
export type Weeks = string[];
export type Id2 = string;
export type Kind2 = "trailing";
export type Label2 = string;
export type Weeks1 = string[];
export type Windows = (AllTimeWindow | SemesterWindow | TrailingWindow)[];

/**
 * Root of the aggregates file. Shape law lives here; semantics in docs/aggregates-contract.md.
 */
export interface Aggregates {
  data_provenance: DataProvenance;
  data_through_date: DataThroughDate;
  data_through_week: DataThroughWeek;
  first_week: FirstWeek;
  footnotes: Footnotes;
  generated_at: GeneratedAt;
  label_versions: LabelVersions;
  pipeline_version: PipelineVersion;
  privacy_floor_n: PrivacyFloorN;
  schema_version: SchemaVersion;
  sections: Sections;
  timezone: Timezone;
  windows: Windows;
  [k: string]: unknown;
}
export interface Footnotes {
  [k: string]: Footnote;
}
export interface Footnote {
  text: Text;
  [k: string]: unknown;
}
export interface LabelVersions {
  [k: string]: string;
}
export interface Sections {
  language?: LanguageSection | null;
  sessions?: SessionsSection | null;
  temporal_usage?: TemporalUsage | null;
  tokens?: TokensSection | null;
  usage_context?: UsageContext | null;
  [k: string]: unknown;
}
export interface LanguageSection {
  per_window: PerWindow;
  weekly: LanguageWeekly;
  [k: string]: unknown;
}
export interface PerWindow {
  [k: string]: LanguageWindow;
}
export interface LanguageWindow {
  totals: LanguageTotals;
  [k: string]: unknown;
}
export interface LanguageTotals {
  de: De;
  en: En;
  other: Other;
  undetermined: Undetermined;
  [k: string]: unknown;
}
export interface OkCell {
  status: Status;
  value: Value;
  [k: string]: unknown;
}
export interface SuppressedCell {
  status: Status1;
  [k: string]: unknown;
}
export interface LanguageWeekly {
  messages_by_language: MessagesByLanguage;
  [k: string]: unknown;
}
export interface MessagesByLanguage {
  de: WeeklySeries;
  en: WeeklySeries;
  footnote_ids?: FootnoteIds1;
  other: WeeklySeries;
  undetermined: WeeklySeries;
  [k: string]: unknown;
}
export interface WeeklySeries {
  footnote_ids?: FootnoteIds;
  series: Series;
  [k: string]: unknown;
}
export interface WeeklyEntry {
  cell: Cell;
  week: Week;
  [k: string]: unknown;
}
export interface SessionsSection {
  per_window: PerWindow1;
  [k: string]: unknown;
}
export interface PerWindow1 {
  [k: string]: SessionsWindow;
}
export interface SessionsWindow {
  messages_per_session: Histogram;
  session_duration_minutes: Histogram;
  [k: string]: unknown;
}
export interface Histogram {
  bins: Bins;
  footnote_ids?: FootnoteIds2;
  n_total: NTotal;
  summary?: Summary;
  unit: Unit;
  [k: string]: unknown;
}
export interface HistogramBin {
  cell: Cell1;
  hi: Hi;
  lo: Lo;
  [k: string]: unknown;
}
export interface OkSummaryStats {
  mean?: Mean;
  median: Median;
  n_students: NStudents;
  p25: P25;
  p75: P75;
  sd?: Sd;
  status: Status2;
  [k: string]: unknown;
}
export interface SuppressedSummaryStats {
  status: Status3;
  [k: string]: unknown;
}
export interface TemporalUsage {
  per_window: PerWindow2;
  weekly: TemporalUsageWeekly;
  [k: string]: unknown;
}
export interface PerWindow2 {
  [k: string]: TemporalUsageWindow;
}
export interface TemporalUsageWindow {
  activity_heatmap: HeatmapGrid;
  [k: string]: unknown;
}
export interface HeatmapGrid {
  cells: Cells;
  footnote_ids?: FootnoteIds3;
  [k: string]: unknown;
}
export interface HeatmapCell {
  cell: Cell2;
  dow: Dow;
  hour: Hour;
  [k: string]: unknown;
}
export interface TemporalUsageWeekly {
  active_students: WeeklySeries;
  messages: WeeklySeries;
  sessions: WeeklySeries;
  [k: string]: unknown;
}
export interface TokensSection {
  per_window: PerWindow3;
  [k: string]: unknown;
}
export interface PerWindow3 {
  [k: string]: TokensWindow;
}
export interface TokensWindow {
  completion_tokens_per_message: Histogram;
  [k: string]: unknown;
}
export interface UsageContext {
  per_window: PerWindow4;
  weekly: UsageContextWeekly;
  [k: string]: unknown;
}
export interface PerWindow4 {
  [k: string]: UsageContextWindow;
}
export interface UsageContextWindow {
  totals: UsageContextTotals;
  user_classes: UserClasses;
  [k: string]: unknown;
}
export interface UsageContextTotals {
  active_students: ActiveStudents;
  messages: Messages;
  new_registrations: NewRegistrations;
  sessions: Sessions;
  [k: string]: unknown;
}
export interface UserClasses {
  footnote_ids?: FootnoteIds4;
  monthly: Monthly;
  one_time: OneTime;
  sporadic: Sporadic;
  [k: string]: unknown;
}
export interface UsageContextWeekly {
  registrations: WeeklySeries;
  [k: string]: unknown;
}
export interface AllTimeWindow {
  coverage: Coverage;
  id: Id;
  kind: Kind;
  label: Label;
  [k: string]: unknown;
}
export interface Coverage {
  from: From;
  through: Through;
  [k: string]: unknown;
}
export interface SemesterWindow {
  coverage: Coverage;
  end_date: EndDate;
  id: Id1;
  kind: Kind1;
  label: Label1;
  start_date: StartDate;
  weeks: Weeks;
  [k: string]: unknown;
}
export interface TrailingWindow {
  coverage: Coverage;
  id: Id2;
  kind: Kind2;
  label: Label2;
  weeks: Weeks1;
  [k: string]: unknown;
}
